/*
 *  Copyright (C) 2002-2021  The DOSBox Team
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License along
 *  with this program; if not, write to the Free Software Foundation, Inc.,
 *  51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 */

#include "config.h"

#include <switch.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>

#include "dosbox.h"
#include "bios_disk.h"
#include "control.h"
#include "cross.h"
#include "setup.h"
#include "mapper.h"
#include "keyboard.h"
#include "programs.h"
#include "savestate.h"
#include "support.h"
#include "drives.h"

#include "mainline.h"
#include "osd.h"
#include "switch_ftp.h"

bool SwitchPlatform_VideoInit(void);
void SwitchPlatform_VideoShutdown(void);
void SwitchPlatform_RecreateFramebuffer(void);
void SwitchPlatform_InputInit(void);
void SwitchPlatform_UpdateModifiers(void);
void SwitchPlatform_AudioShutdown(void);
void SwitchPlatform_ResetSession(void);
void SwitchPlatform_ResetInput(void);
void SwitchPlatform_ShowFatal(const char *title, const char *detail);
void SwitchPlatform_TraceClose(void);

static void SwitchPlatform_ReportError(const char *label, const char *detail) {
	char title[64];
	snprintf(title, sizeof(title), "%.52s", detail ? detail : label);
	char body[1024];
	snprintf(body, sizeof(body), "%s: %s", label, detail ? detail : "(no detail)");
	SwitchPlatform_ShowFatal(title, body);
}
void SwitchPlatform_Trace(const char *step);
void SwitchPlatform_OSDInit(void);
void ConsoleMapper_ResetBinds(void);

extern "C" {
int __stack_size = 0x400000;
}

#define SWITCH_BOOT_CONF "sdmc:/dosbox/boot.conf"

static char boot_cmdline[2176] = "";

static bool write_boot_config(const char *folder, const char *images,
                              const char *boot_cmds, const char *mount_drive) {
	FILE *f = fopen(SWITCH_BOOT_CONF, "w");
	if (!f) return false;

	const bool is_floppy = mount_drive && (mount_drive[0] == 'a' || mount_drive[0] == 'A');

	fputs("# Generated by DOSBox at start up: the folder and the disk images\n"
	      "# picked in the launcher. Safe to delete, rewritten on every start.\n"
	      "[autoexec]\n", f);
	if (folder && folder[0]) {
		fprintf(f, "mount c \"%s\"\n", folder);
		fputs("c:\n", f);
	}

	if (images && images[0]) {
		fprintf(f, "imgmount %c", is_floppy ? 'a' : 'd');
		const char *p = images;
		while (*p) {
			while (*p == '\r' || *p == '\n') p++;
			if (!*p) break;
			const char *e = p;
			while (*e && *e != '\r' && *e != '\n') e++;
			fprintf(f, " \"%.*s\"", (int)(e - p), p);
			p = e;
		}
		fputs(is_floppy ? " -t floppy\n" : " -t iso\n", f);
	}

	bool wrote_cmds = false;
	for (const char *line = boot_cmds; line && *line;) {
		const char *nl = strchr(line, '\n');
		const int len = nl ? (int)(nl - line) : (int)strlen(line);
		if (len) {
			fprintf(f, "%.*s\n", len, line);
			wrote_cmds = true;
		}
		line = nl ? nl + 1 : NULL;
	}

	if (!wrote_cmds) {
		if (images && images[0]) {
			fprintf(f, "%c:\n", is_floppy ? 'a' : 'd');
		} else if (folder && folder[0]) {
			fputs("if exist autoexec.bat call autoexec.bat\n", f);
		}
	}
	fclose(f);
	return true;
}

static void SwitchPlatform_AppletHook(AppletHookType hook, void *param) {
	if (hook == AppletHookType_OnOperationMode) {
		AppletMessage msg = *(AppletMessage *)param;
		if (msg == AppletMessage_OperationModeChanged) {
			SwitchPlatform_RecreateFramebuffer();
		}
	}
	
	if (hook == AppletHookType_OnExitRequest) {
		SwitchPlatform_Trace("exit request: cleaning up state");
		SwitchPlatform_AudioShutdown();
		SwitchPlatform_ResetInput();
		SwitchPlatform_ResetSession();
		KEYBOARD_ClrBuffer();
		MAPPER_LosingFocus();
		ConsoleMapper_ResetBinds();
		SwitchPlatform_Trace("exit request: cleanup done");
	}
	
	if (hook == AppletHookType_OnResume) {
		SwitchPlatform_Trace("resume: reacquiring input");
		SwitchPlatform_ResetInput();
		KEYBOARD_ClrBuffer();
		MAPPER_LosingFocus();
		SwitchPlatform_Trace("resume: input ready");
	}

	if (hook == AppletHookType_OnFocusState) {
		if (appletGetFocusState() == AppletFocusState_InFocus) {
			SwitchPlatform_ResetInput();
		}
	}
}

int main(int argc, char *argv[]) {
	Result rc = 0;
	if (R_FAILED(rc = appletInitialize())) {
		fprintf(stderr, "appletInitialize failed: 0x%08x\n", rc);
		return 1;
	}

	mkdir("sdmc:/dosbox", 0777);
	mkdir("sdmc:/dosbox/games", 0777);
	mkdir("sdmc:/dosbox/savestates", 0777);
	SAVESTATE_SetDirectory("sdmc:/dosbox/savestates");
	static char home[] = "sdmc:/dosbox";
	setenv("HOME", home, 1);

	romfsInit();

	static AppletHookCookie applet_hook;
	appletHook(&applet_hook, SwitchPlatform_AppletHook, NULL);
	appletSetCpuBoostMode(ApmCpuBoostMode_FastLoad);

	if (!SwitchPlatform_VideoInit()) {
		fprintf(stderr, "Could not create the framebuffer\n");
		SwitchPlatform_ShowFatal("DOSBox: no video output",
		                         "The framebuffer could not be created.");
		appletExit();
		return 1;
	}
	SwitchPlatform_InputInit();
	
	SwitchPlatform_Trace("startup: cleaning residual state");
	SwitchPlatform_AudioShutdown();
	SwitchPlatform_ResetSession();
	SwitchPlatform_ResetInput();
	KEYBOARD_ClrBuffer();
	MAPPER_LosingFocus();
	ConsoleMapper_ResetBinds();
	SwitchPlatform_Trace("startup: cleanup done");
	
	SwitchPlatform_VideoShutdown();
	if (!SwitchPlatform_VideoInit()) {
		fprintf(stderr, "Could not recreate the framebuffer\n");
		SwitchPlatform_ShowFatal("DOSBox: no video output",
		                         "The framebuffer could not be recreated.");
		appletExit();
		return 1;
	}
	
	SwitchPlatform_Trace("video+input ready");

	while (appletMainLoop()) {
		SwitchPlatform_OSDInit();
		SwitchPlatform_Trace("osd init");
		
		KEYBOARD_ClrBuffer();
		MAPPER_LosingFocus();
		ConsoleMapper_ResetBinds();
		
		extern void TIMER_ClearTickHandlers(void);
		TIMER_ClearTickHandlers();
		
		static char image_list[1024];
		static char boot_cmds[512];
		static char mount_drive[2];
		image_list[0] = '\0';
		boot_cmds[0] = '\0';
		mount_drive[0] = 'd';
		const char *mount_path = OSD_RunLauncher(image_list, sizeof(image_list),
		                                          boot_cmds, sizeof(boot_cmds),
		                                          mount_drive, sizeof(mount_drive));
		if (!mount_path) {
			SwitchPlatform_Trace("user quit from launcher");
			break;
		}
		SwitchPlatform_Trace("launcher done");

		{
			char state_dir[CROSS_LEN];
			char game_name[CROSS_LEN];
			size_t len = strlen(mount_path);
			while (len && (mount_path[len - 1] == '/' || mount_path[len - 1] == '\\')) len--;
			if (strcmp(mount_path, "sdmc:/") != 0 && len &&
			    len + sizeof("/savestates") <= sizeof(state_dir)) {
				snprintf(state_dir, sizeof(state_dir), "%.*s/savestates", (int)len, mount_path);
				SAVESTATE_SetDirectory(state_dir);
				size_t start = len;
				while (start && mount_path[start - 1] != '/' && mount_path[start - 1] != '\\') start--;
				snprintf(game_name, sizeof(game_name), "%.*s",
				         (int)(len - start), mount_path + start);
				SAVESTATE_SetGameName(game_name);
			} else {
				SAVESTATE_SetDirectory("sdmc:/dosbox/savestates");
				SAVESTATE_SetGameName("");
			}
		}

	try {
		bool boot_conf = false;
		if (write_boot_config(mount_path, image_list, boot_cmds, mount_drive)) {
			boot_conf = true;
			SwitchPlatform_Trace("boot config:");
			SwitchPlatform_Trace(mount_path ? mount_path : "(no folder)");
			SwitchPlatform_Trace(image_list[0] ? image_list : "(no images)");
			{
				char drive_line[64];
				snprintf(drive_line, sizeof(drive_line), "mount drive: %c:",
				         (mount_drive[0] == 'a' || mount_drive[0] == 'A') ? 'A' : 'D');
				SwitchPlatform_Trace(drive_line);
			}
			SwitchPlatform_Trace(boot_cmds[0] ? boot_cmds : "(no start program)");
		} else {
			char cmdline[2048];
			size_t used = 0;
			int n = snprintf(cmdline, sizeof(cmdline), "dosbox");
			used = (size_t)(n > 0 ? n : 0);
			if (mount_path && mount_path[0])
				n = snprintf(cmdline + used, sizeof(cmdline) - used,
				             " -c \"mount c %s\"", mount_path);
			used += (size_t)(n > 0 ? n : 0);
			if (image_list[0]) {
				const char letter = (mount_drive[0] == 'a' ||
				                     mount_drive[0] == 'A') ? 'a' : 'd';
				n = snprintf(cmdline + used, sizeof(cmdline) - used,
				             " -c \"imgmount %c %s\"", letter, image_list);
				used += (size_t)(n > 0 ? n : 0);
			}
			bool wrote_cmds = false;
			for (const char *line = boot_cmds; line && *line;) {
				const char *nl = strchr(line, '\n');
				const size_t len = nl ? (size_t)(nl - line) : strlen(line);
				if (len) {
					char one[256];
					const size_t copy = len < sizeof(one) - 1 ? len : sizeof(one) - 1;
					memcpy(one, line, copy);
					one[copy] = '\0';
					n = snprintf(cmdline + used, sizeof(cmdline) - used, " -c \"%s\"", one);
					used += (size_t)(n > 0 ? n : 0);
					wrote_cmds = true;
				}
				line = nl ? nl + 1 : NULL;
			}
			if (!wrote_cmds && image_list[0]) {
				n = snprintf(cmdline + used, sizeof(cmdline) - used, " -c \"boot d:\"");
				used += (size_t)(n > 0 ? n : 0);
			}
			snprintf(boot_cmdline, sizeof(boot_cmdline), "%s", cmdline);
		}

		char cmdline[2176];
		snprintf(cmdline, sizeof(cmdline), "dosbox%s", boot_conf
		         ? " -conf " SWITCH_BOOT_CONF : "");
		if (!boot_conf) {
			strncat(cmdline, boot_cmdline + strlen("dosbox"),
			        sizeof(cmdline) - strlen(cmdline) - 1);
		}
		SwitchPlatform_Trace(cmdline);

		CommandLine com_line("dosbox", cmdline);
		Config myconf(&com_line);
		control = &myconf;
		ConsoleMapper_ResetBinds();
		SwitchPlatform_Trace("DOSBOX_Init");
		DOSBOX_Init();
		Config_Add_Target();
		SwitchPlatform_Trace("config sections registered");

		if (control->cmdline->FindExist("-version") ||
		    control->cmdline->FindExist("--version")) {
			printf("\nNX-DOSBox 1.00 (DOSBox %s core) for Nintendo Switch - TheheroGAC.\n"
			       "DOSBox is copyright 2002-2021 The DOSBox Team, GPLv2.\n\n",
			       VERSION);
			return 0;
		}

		std::string config_file, config_path, config_combined;
		Cross::GetPlatformConfigDir(config_path);

		while (control->cmdline->FindString("-conf", config_file, true)) {
			if (!control->ParseConfigFile(config_file.c_str())) {
				if (!control->ParseConfigFile((config_path + config_file).c_str())) {
					LOG_MSG("CONFIG: Can't open specified config file: %s", config_file.c_str());
				}
			}
		}
		if (boot_conf) {
			if (!control->ParseConfigFile("dosbox.conf"))
				control->ParseConfigFile((config_path + "dosbox.conf").c_str());
		}
		if (!control->configfiles.size()) control->ParseConfigFile("dosbox.conf");

		if (!control->configfiles.size()) {
			config_file.clear();
			Cross::GetPlatformConfigName(config_file);
			control->ParseConfigFile((config_path + config_file).c_str());
		}

		if (!control->configfiles.size()) {
			config_file.clear();
			Cross::CreatePlatformConfigDir(config_path);
			Cross::GetPlatformConfigName(config_file);
			config_combined = config_path + config_file;
			if (control->PrintConfig(config_combined.c_str())) {
				LOG_MSG("CONFIG: Generating default configuration.\nWriting it to %s",
				         config_combined.c_str());
				control->ParseConfigFile(config_combined.c_str());
			} else {
				LOG_MSG("CONFIG: Using default settings.");
			}
		}

		if (control->ParseConfigFile("sdmc:/dosbox/settings.conf"))
			SwitchPlatform_Trace("settings.conf applied");

		if (Section *mixer_sec = control->GetSection("mixer")) {
			static_cast<Section_prop *>(mixer_sec)->HandleInputline("prebuffer=60");
		}

		SwitchPlatform_Trace("control->Init");
		control->Init();
		Config_ApplyConsoleDefaults();

		BIOS_SetAutoDiskSwap(false);
		if (image_list[0]) {
			int images = 1;
			for (const char *p = image_list; *p; p++) {
				if (*p == '\n') images++;
			}
			if (images > 1) {
				BIOS_SetAutoDiskSwap(true);
				SwitchPlatform_Trace("disk set: automatic image swap on");
			}
		}

		SwitchPlatform_Trace("MAPPER_Init");
		MAPPER_Init();
		if (control->cmdline->FindExist("-startmapper")) MAPPER_RunInternal();

		SwitchPlatform_Trace("control->StartUp");
	char hint[128];
	const char *program = NULL;
	for (const char *line = boot_cmds; line && *line;) {
		const char *nl = strchr(line, '\n');
		if (nl ? (nl != line) : *line) program = line;
		line = nl ? nl + 1 : NULL;
	}
	if (program) {
		char name[96];
		const char *e = strpbrk(program, "\n");
		const size_t len = e ? (size_t)(e - program) : strlen(program);
		snprintf(name, sizeof(name), "%.*s", (int)len, program);
		snprintf(hint, sizeof(hint), "STARTING %s", name);
		OSD_ShowSessionHint(hint);
	} else if (image_list[0]) {
		OSD_ShowSessionHint("DISKS ON D: - PRESS L3 TO TYPE");
	} else if (strcmp(mount_path, "sdmc:/") == 0) {
		OSD_ShowSessionHint("CLASSIC DOSBOX - C: IS THE SD CARD - PRESS L3 TO TYPE");
	} else {
		OSD_ShowSessionHint("NO START PROGRAM FOUND - PRESS L3 TO TYPE");
	}
		SwitchPlatform_ResetInput();
		control->StartUp();
		SwitchPlatform_Trace("machine stopped");
		} catch (int code) {
			if (code == 1) {
				LOG_MSG("Exit code 1 (user requested quit)");
				SwitchPlatform_Trace("session ended, quit to Horizon/hbmenu requested");
				control = NULL;
				break;
			}
			LOG_MSG("Exit code %d (returning to launcher)", code);
			SwitchPlatform_Trace("session ended, back to the launcher");
			control = NULL;
			SwitchPlatform_AudioShutdown();
			SwitchPlatform_Trace("session: audio closed");
			SwitchPlatform_ResetInput();
			SwitchPlatform_ResetSession();
			SwitchPlatform_Trace("session: video and input reset");
			OSD_CloseOverlays();
			SwitchPlatform_Trace("session torn down, launcher next");
			
			BIOS_SetAutoDiskSwap(false);
			DriveManager::ShutDown();
			ConsoleMapper_ResetBinds();
			continue;
		} catch (char *error) {
			LOG_MSG("Exit to error: %s", error);
			control = NULL;
			{
				char msg[600];
				snprintf(msg, sizeof(msg), "fatal: %s", error ? error : "(no detail)");
				SwitchPlatform_Trace(msg);
			}
			SwitchPlatform_ReportError("NX-DOSBox E_Exit", error);
			break;
		} catch (...) {
			control = NULL;
			SwitchPlatform_Trace("fatal: unknown C++ exception");
			SwitchPlatform_ReportError("NX-DOSBox exception", "unknown C++ exception");
			break;
		}
		SwitchPlatform_AudioShutdown();
		OSD_CloseOverlays();
	}

	SwitchPlatform_Trace("exit: ftp");
	SwitchPlatform_FTPShutdown();
	fsdevCommitDevice("sdmc");
	SwitchPlatform_Trace("exit: card committed");
	SwitchPlatform_Trace("exit: audio");
	SwitchPlatform_AudioShutdown();
	SwitchPlatform_Trace("exit: video");
	SwitchPlatform_VideoShutdown();
	SwitchPlatform_Trace("exit: overlays");
	OSD_Shutdown();
	romfsExit();
	SwitchPlatform_Trace("exit: done");
	SwitchPlatform_TraceClose();
	appletExit();
	return 0;
}
